In [1]:
# Gold, Bronze - Complete
# Silver - Drafting

In [2]:
import pandas as pd
import matplotlib.pyplot as plt

# Gold

In [3]:
# Load data
male_sports_df = pd.read_csv('Male-Sports/male_athletes_gold.csv')
male_sports_df.head()
# male_sports_df.shape

,NOC,Name,Sex,Age,Height,Weight,Season,Year,Sport,Event,Medal
0,FIN,Paavo Johannes Aaltonen,M,28.0,175.0,64.0,Summer,1948,Gymnastics,Gymnastics Men's Team All-Around,Gold
1,FIN,Paavo Johannes Aaltonen,M,28.0,175.0,64.0,Summer,1948,Gymnastics,Gymnastics Men's Horse Vault,Gold
2,FIN,Paavo Johannes Aaltonen,M,28.0,175.0,64.0,Summer,1948,Gymnastics,Gymnastics Men's Pommelled Horse,Gold
3,NOR,Kjetil Andr Aamodt,M,20.0,176.0,85.0,Winter,1992,Alpine Skiing,Alpine Skiing Men's Super G,Gold
4,NOR,Kjetil Andr Aamodt,M,30.0,176.0,85.0,Winter,2002,Alpine Skiing,Alpine Skiing Men's Super G,Gold

In [4]:
# Dropping every row with 1 Olympian only 

male_sports_df = male_sports_df[(male_sports_df.Event != "Cross Country Skiing Men's 10/15 kilometres Pursuit") &
                                (male_sports_df.Event != "Gymnastics Men's Rope Climbing") &
                                (male_sports_df.Event != "Athletics Men's 1,500 metres Walk") &
                                (male_sports_df.Event != "Freestyle Skiing Men's Slopestyle") &
                                (male_sports_df.Event != "Swimming Men's 220 yard Freestyle") &
                                (male_sports_df.Event != "Swimming Men's 440 yard Freestyle") &
                                (male_sports_df.Event != "Swimming Men's 4 x 50 Yard Freestyle Relay") &
                                (male_sports_df.Event != "Nordic Combined Men's Large Hill / 10 km, Individual") &
                                (male_sports_df.Event != "Athletics Men's 3,000 metres Walk") &
                                (male_sports_df.Event != "Athletics Men's Stone Throw") &
                                (male_sports_df.Event != "Art Competitions Mixed Architecture, Architectural Designs") &
                                (male_sports_df.Event != "Equestrianism Men's Jumping, Individual") &
                                (male_sports_df.Event != "Sailing Mixed Windsurfer") &
                                (male_sports_df.Event != "Snowboarding Men's Slopestyle") &
                                (male_sports_df.Event != "Athletics Men's 3,500 metres Walk") &
                                (male_sports_df.Event != "Athletics Men's 10 mile Walk") &
                                (male_sports_df.Event != "Cross Country Skiing Men's 18 kilometres") &
                                (male_sports_df.Event != "Equestrianism Men's Three-Day Event, Individual") &
                                (male_sports_df.Event != "Athletics Men's 2,500 metres Steeplechase") &
                                (male_sports_df.Event != "Athletics Men's Javelin Throw, Both Hands") &
                                (male_sports_df.Event != "Athletics Men's 3,200 metres Steeplechase") &
                                (male_sports_df.Event != "Wrestling Men's Unlimited Class, Greco-Roman") &
                                (male_sports_df.Event != "Gymnastics Men's Team All-Around, Swedish System") &
                                (male_sports_df.Event != "Athletics Men's Discus Throw, Both Hands") &
                                (male_sports_df.Event != "Athletics Men's 5 mile") &
                                (male_sports_df.Event != "Snowboarding Men's Parallel Slalom") &
                                (male_sports_df.Event != "Athletics Men's 2,590 metres Steeplechase") &
                                (male_sports_df.Event != "Athletics Men's Pentathlon (Ancient)") &
                                (male_sports_df.Event != "Snowboarding Men's Giant Slalom") &
                                (male_sports_df.Event != "Gymnastics Men's Parallel Bars, Teams") &
                                (male_sports_df.Event != "Gymnastics Men's Horizontal Bar, Teams") &
                                (male_sports_df.Event != "Swimming Men's One Mile Freestyle") &
                                (male_sports_df.Event != "Speed Skating Men's Allround") &
                                (male_sports_df.Event != "Canoeing Men's Canadian Doubles, 10,000 metres") &
                                (male_sports_df.Event != "Cross Country Skiing Men's 10 kilometres") &
                                (male_sports_df.Event != "Swimming Men's 50 yard Freestyle") &
                                (male_sports_df.Event != "Swimming Men's 100 yard Freestyle") &
                                (male_sports_df.Event != "Swimming Men's 4 x 250 metres Freestyle Relay") &
                                (male_sports_df.Event != "Freestyle Skiing Men's Halfpipe") &
                                (male_sports_df.Event != "Athletics Men's Shot Put, Both Hands") &
                                (male_sports_df.Event != "Athletics Men's 1,600 metres Medley Relay") &
                                (male_sports_df.Event != "Athletics Men's 3 mile, Team")
                                ]
# male_sports_df.head()

# Cross Country Skiing Men's 10/15 kilometres Pursuit: Winter 1998
# Gymnastics Men's Rope Climbing: Summer 1932
# Athletics Men's 1,500 metres Walk: Summer 1906
# Freestyle Skiing Men's Slopestyle: Winter 2014
# Swimming Men's 220 yard Freestyle: Summer 1904
# Swimming Men's 440 yard Freestyle: Summer 1904
# Swimming Men's 4 x 50 Yard Freestyle Relay:Summer 1904
# Nordic Combined Men's Large Hill / 10 km, Individual: Winter 2010
# Athletics Men's 3,000 metres Walk: Summer 1920
# Athletics Men's Stone Throw: Summer 1906
# Art Competitions Mixed Architecture, Architectural Designs: Summer 1948
# Equestrianism Men's Jumping, Individual: Summer 1952
# Sailing Mixed Windsurfer: Summer 1988
# Snowboarding Men's Slopestyle: Winter 2014
# Athletics Men's 3,500 metres Walk: Summer 1908
# Athletics Men's 10 mile Walk: Summer 1908
# Cross Country Skiing Men's 18 kilometres: Winter 1936
# Athletics Men's 2,590 metres Steeplechase: Summer 1904
# Athletics Men's Pentathlon (Ancient): Summer 1906
# Equestrianism Men's Three-Day Event, Individual: Summer 1960
# Athletics Men's 2,500 metres Steeplechase: Summer 1900
# Athletics Men's Javelin Throw, Both Hands: Summer 1912
# Athletics Men's 3,200 metres Steeplechase: Summer 1908
# Wrestling Men's Unlimited Class, Greco-Roman: Summer 1896
# Gymnastics Men's Team All-Around, Swedish System: Summer 1912
# Athletics Men's Discus Throw, Both Hands: Summer 1912
# Athletics Men's 5 mile: Summer 1908
# Snowboarding Men's Parallel Slalom: Winter 2014
# Athletics Men's 2,590 metres Steeplechase: Summer 1904
# Snowboarding Men's Giant Slalom: Winter 1988
# Gymnastics Men's Parallel Bars, Teams: Summer 1896
# Gymnastics Men's Horizontal Bar, Teams: Summer 1896
# Swimming Men's One Mile Freestyle: Summer 1906
# Speed Skating Men's Allround: Winter 1924
# Canoeing Men's Canadian Doubles, 10,000 metres: Summer 1952
# Athletics Men's 1,600 metres Medley Relay - One in Bronze
# Athletics Men's 3 mile, Team - One in Bronze

In [5]:
# Get unique name of event
event_list = male_sports_df.Event.unique()

# Create empty age, height, weight lists for storage
gold_age_list = []
gold_height_list = []
gold_weight_list = []

for event_name in event_list:
    #print(event_name)
    def event_function(event_name):
        
        # Filtering DataFrame for specific event name
        df = male_sports_df.loc[(male_sports_df['Event'] == event_name ),:]

        # Creating the Boxplot
        age_plot = df.loc[df['Event'] == event_name]['Age']
        height_plot = df.loc[df['Event'] == event_name]['Height']
        weight_plot = df.loc[df['Event'] == event_name]['Weight']

#         outlier_markers = dict(marker = 'o' , markerfacecolor='r', 
#                                markersize=5, markeredgecolor='r')
#         plt.boxplot([age_plot, height_plot, weight_plot], 
#                     labels=['Age', 'Height', 'Weight'], 
#                     flierprops=outlier_markers)
#         plt.ylabel('Gold Medals')
#         plt.title(f'Male-{event_name}')

#         #plt.savefig(f'Male-Sport-Events/Plots/Male-{event_name}.png')
#         plt.show()

        # Calculate the quartiles
        age_quartiles = age_plot.quantile([.25,.5,.75])
        height_quartiles = height_plot.quantile([.25,.5,.75])
        weight_quartiles = weight_plot.quantile([.25,.5,.75])
        
        # Creating age list
        age = round(age_quartiles[.5])
        gold_age_list.append(age)
        
        # Creating height list - converting Metric System to Imperial system
        height = (height_quartiles[.5])/30.48
        gold_height_list.append("%.2f"%height)
        
        # Creating weight list - converting Metric System to Imperial system
        weight = (weight_quartiles[.5])*2.205
        gold_weight_list.append("%.2f"%weight)
        
    event_function(event_name)
# print(f'Gold Age List: {gold_age_list}')
# print(f'Gold Height List: {gold_height_list}')
# print(f'Gold Weight List: {gold_weight_list}')

In [6]:
# Finding out length of each list 
print(len(gold_age_list))
print(len(gold_height_list))
print(len(gold_weight_list))
print(len(event_list))

297
297
297
297

In [7]:
# Storing values from list to make a DataFrame
gold_dictionary = {"Event":event_list,"Age":gold_age_list, "Height": gold_height_list, 
                    "Weight":gold_weight_list, "Sex": "Male" }

gold_bodycomp_age_df = pd.DataFrame(gold_dictionary)
gold_bodycomp_age_df.head()

                              Event   Age Height  Weight   Sex
0  Gymnastics Men's Team All-Around  23.0   5.35  130.09  Male
1      Gymnastics Men's Horse Vault  24.0   5.43  137.81  Male
2  Gymnastics Men's Pommelled Horse  23.0   5.54  134.50  Male
3       Alpine Skiing Men's Super G  28.0   5.91  187.43  Male
4      Alpine Skiing Men's Combined  26.0   5.86  179.71  Male

In [8]:
# Saving Dataframe into a csv file
gold_bodycomp_age_df.to_csv('Male-Events/male_gold_bodycomp_age.csv', index=False)

In [9]:
# Saving Dataframe into a JSON file
gold_bodycomp_age_df.to_json('Male-Events/male_gold_bodycomp_age.json')

# Silver

In [10]:
# Load data
male_sports_df = pd.read_csv('Male-Sports/male_athletes_silver.csv')
male_sports_df.head()

,NOC,Name,Sex,Age,Height,Weight,Season,Year,Sport,Event,Medal
0,NOR,Kjetil Andr Aamodt,M,22.0,176.0,85.0,Winter,1994,Alpine Skiing,Alpine Skiing Men's Downhill,Silver
1,NOR,Kjetil Andr Aamodt,M,22.0,176.0,85.0,Winter,1994,Alpine Skiing,Alpine Skiing Men's Combined,Silver
2,NED,Pepijn Aardewijn,M,26.0,189.0,72.0,Summer,1996,Rowing,Rowing Men's Lightweight Double Sculls,Silver
3,FRA,Luc Abalo,M,31.0,182.0,86.0,Summer,2016,Handball,Handball Men's Handball,Silver
4,USA,Stephen Anthony Abas,M,26.0,165.0,55.0,Summer,2004,Wrestling,"Wrestling Men's Featherweight, Freestyle",Silver

In [11]:
# Dropping every row with 1 Olympian only

male_sports_df = male_sports_df[(male_sports_df.Event != "Cross Country Skiing Men's 10/15 kilometres Pursuit") &
                                (male_sports_df.Event != "Gymnastics Men's Rope Climbing") &
                                (male_sports_df.Event != "Athletics Men's 1,500 metres Walk") &
                                (male_sports_df.Event != "Freestyle Skiing Men's Slopestyle") &
                                (male_sports_df.Event != "Swimming Men's 220 yard Freestyle") &
                                (male_sports_df.Event != "Swimming Men's 440 yard Freestyle") &
                                (male_sports_df.Event != "Swimming Men's 4 x 50 Yard Freestyle Relay") &
                                (male_sports_df.Event != "Nordic Combined Men's Large Hill / 10 km, Individual") &
                                (male_sports_df.Event != "Athletics Men's 3,000 metres Walk") &
                                (male_sports_df.Event != "Athletics Men's Stone Throw") &
                                (male_sports_df.Event != "Art Competitions Mixed Architecture, Architectural Designs") &
                                (male_sports_df.Event != "Equestrianism Men's Jumping, Individual") &
                                (male_sports_df.Event != "Sailing Mixed Windsurfer") &
                                (male_sports_df.Event != "Snowboarding Men's Slopestyle") &
                                (male_sports_df.Event != "Athletics Men's 3,500 metres Walk") &
                                (male_sports_df.Event != "Athletics Men's 10 mile Walk") &
                                (male_sports_df.Event != "Cross Country Skiing Men's 18 kilometres") &
                                (male_sports_df.Event != "Equestrianism Men's Three-Day Event, Individual") &
                                (male_sports_df.Event != "Athletics Men's 2,500 metres Steeplechase") &
                                (male_sports_df.Event != "Athletics Men's Javelin Throw, Both Hands") &
                                (male_sports_df.Event != "Athletics Men's 3,200 metres Steeplechase") &
                                (male_sports_df.Event != "Wrestling Men's Unlimited Class, Greco-Roman") &
                                (male_sports_df.Event != "Gymnastics Men's Team All-Around, Swedish System") &
                                (male_sports_df.Event != "Athletics Men's Discus Throw, Both Hands") &
                                (male_sports_df.Event != "Athletics Men's 5 mile") &
                                (male_sports_df.Event != "Snowboarding Men's Parallel Slalom") &
                                (male_sports_df.Event != "Athletics Men's 2,590 metres Steeplechase") &
                                (male_sports_df.Event != "Athletics Men's Pentathlon (Ancient)") &
                                (male_sports_df.Event != "Snowboarding Men's Giant Slalom") &
                                (male_sports_df.Event != "Gymnastics Men's Parallel Bars, Teams") &
                                (male_sports_df.Event != "Gymnastics Men's Horizontal Bar, Teams") &
                                (male_sports_df.Event != "Swimming Men's One Mile Freestyle") &
                                (male_sports_df.Event != "Speed Skating Men's Allround") &
                                (male_sports_df.Event != "Canoeing Men's Canadian Doubles, 10,000 metres") &
                                (male_sports_df.Event != "Cross Country Skiing Men's 10 kilometres") &
                                (male_sports_df.Event != "Swimming Men's 50 yard Freestyle") &
                                (male_sports_df.Event != "Swimming Men's 100 yard Freestyle") &
                                (male_sports_df.Event != "Swimming Men's 4 x 250 metres Freestyle Relay") &
                                (male_sports_df.Event != "Freestyle Skiing Men's Halfpipe") &
                                (male_sports_df.Event != "Athletics Men's Shot Put, Both Hands")&
                                (male_sports_df.Event != "Weightlifting Men's Unlimited, One Hand") &
                                (male_sports_df.Event != "Canoeing Men's Folding Kayak Singles, 10 kilometres") &
                                (male_sports_df.Event != "Cycling Men's Road Race, Team") &
                                (male_sports_df.Event != "Diving Men's Plain High") &
                                (male_sports_df.Event != "Wrestling Men's Middleweight A, Greco-Roman") &
                                (male_sports_df.Event != "Canoeing Men's Kayak Doubles, 10,000 metres") &
                                (male_sports_df.Event != "Sailing Mixed 6.5 metres") &
                                (male_sports_df.Event != "Athletics Men's 5,000 metres, Team") &
                                (male_sports_df.Event != "Cycling Men's 5,000 metres") &
                                (male_sports_df.Event != "Nordic Combined Men's Normal Hill / 10 km, Individual") &
                                (male_sports_df.Event != "Golf Men's Individual") &
                                (male_sports_df.Event != "Athletics Men's 10 kilometres Walk") &
                                (male_sports_df.Event != "Wrestling Men's All-Around, Greco-Roman") &
                                (male_sports_df.Event != "Athletics Men's 60 metres") &
                                (male_sports_df.Event != "ASwimming Men's 4,000 metres Freestyle")

                                ]
# male_sports_df.head()

In [1]:
# event_list = male_sports_df.Event.unique()
# for event_name in event_list:
#     print(event_name)

In [13]:
# Get unique name of event
event_list = male_sports_df.Event.unique()

# Create empty age, height, weight lists for storage
silver_age_list = []
silver_height_list = []
silver_weight_list = []

for event_name in event_list:
    # print(event_name)
    def event_function(event_name):
        
        # Filtering DataFrame for specific event name
        df = male_sports_df.loc[(male_sports_df['Event'] == event_name ),:]

        # Creating the Boxplot
        age_plot = df.loc[df['Event'] == event_name]['Age']
        height_plot = df.loc[df['Event'] == event_name]['Height']
        weight_plot = df.loc[df['Event'] == event_name]['Weight']

#         outlier_markers = dict(marker = 'o' , markerfacecolor='r', 
#                                markersize=5, markeredgecolor='r')
#         plt.boxplot([age_plot, height_plot, weight_plot], 
#                     labels=['Age', 'Height', 'Weight'], 
#                     flierprops=outlier_markers)
#         plt.ylabel('Silver Medals')
#         plt.title(f'Male-{event_name}')

#         #plt.savefig(f'Male-Sport-Events/Plots/male-{event_name}.png')
#         plt.show()

        # Calculate the quartiles
        age_quartiles = age_plot.quantile([.25,.5,.75])
        height_quartiles = height_plot.quantile([.25,.5,.75])
        weight_quartiles = weight_plot.quantile([.25,.5,.75])
        
        # Creating age list
        age = round(age_quartiles[.5])
        silver_age_list.append(age)
        
        # Creating height list - converting Metric System to Imperial system
        height = (height_quartiles[.5])/30.48
        silver_height_list.append("%.2f"%height)
        
        # Creating weight list - converting Metric System to Imperial system
        weight = (weight_quartiles[.5])*2.205
        silver_weight_list.append("%.2f"%weight)
        
    event_function(event_name)
# print(f'Silver Age List: {silver_age_list}')
# print(f'Silver Height List: {silver_height_list}')
# print(f'Silver Weight List: {silver_weight_list}')

In [14]:
# Finding out length of each list 
print(len(silver_age_list))
print(len(silver_height_list))
print(len(silver_weight_list))
print(len(event_list))

291
291
291
291

In [15]:
# Storing values from list to make a DataFrame
silver_dictionary = {"Event":event_list,"Age":silver_age_list, "Height": silver_height_list, 
                    "Weight":silver_weight_list, "Sex": "Male"  }

silver_bodycomp_age_df = pd.DataFrame(silver_dictionary)
silver_bodycomp_age_df.head()

                                      Event   Age Height  Weight   Sex
0              Alpine Skiing Men's Downhill  27.0   5.94  185.22  Male
1              Alpine Skiing Men's Combined  25.0   5.97  194.04  Male
2    Rowing Men's Lightweight Double Sculls  26.0   5.94  157.66  Male
3                   Handball Men's Handball  27.0   6.23  198.45  Male
4  Wrestling Men's Featherweight, Freestyle  25.0   5.51  136.71  Male

In [16]:
# Saving Dataframe into a csv file
silver_bodycomp_age_df.to_csv('Male-Events/male_silver_bodycomp_age.csv', index=False)

In [17]:
# Saving Dataframe into a JSON file
silver_bodycomp_age_df.to_json('Male-Events/male_silver_bodycomp_age.json')

# Bronze

In [18]:
# Load data
male_sports_df = pd.read_csv('Male-Sports/male_athletes_bronze.csv')
male_sports_df.head()

,NOC,Name,Sex,Age,Height,Weight,Season,Year,Sport,Event,Medal
0,FIN,Juhamatti Tapio Aaltonen,M,28.0,184.0,85.0,Winter,2014,Ice Hockey,Ice Hockey Men's Ice Hockey,Bronze
1,FIN,Paavo Johannes Aaltonen,M,28.0,175.0,64.0,Summer,1948,Gymnastics,Gymnastics Men's Individual All-Around,Bronze
2,FIN,Paavo Johannes Aaltonen,M,32.0,175.0,64.0,Summer,1952,Gymnastics,Gymnastics Men's Team All-Around,Bronze
3,NOR,Kjetil Andr Aamodt,M,20.0,176.0,85.0,Winter,1992,Alpine Skiing,Alpine Skiing Men's Giant Slalom,Bronze
4,NOR,Kjetil Andr Aamodt,M,22.0,176.0,85.0,Winter,1994,Alpine Skiing,Alpine Skiing Men's Super G,Bronze

In [19]:
# Dropping every row with 1 Olympian only

male_sports_df = male_sports_df[(male_sports_df.Event != "Cross Country Skiing Men's 10/15 kilometres Pursuit") &
                                (male_sports_df.Event != "Gymnastics Men's Rope Climbing") &
                                (male_sports_df.Event != "Athletics Men's 1,500 metres Walk") &
                                (male_sports_df.Event != "Freestyle Skiing Men's Slopestyle") &
                                (male_sports_df.Event != "Swimming Men's 220 yard Freestyle") &
                                (male_sports_df.Event != "Swimming Men's 440 yard Freestyle") &
                                (male_sports_df.Event != "Swimming Men's 4 x 50 Yard Freestyle Relay") &
                                (male_sports_df.Event != "Nordic Combined Men's Large Hill / 10 km, Individual") &
                                (male_sports_df.Event != "Athletics Men's 3,000 metres Walk") &
                                (male_sports_df.Event != "Athletics Men's Stone Throw") &
                                (male_sports_df.Event != "Art Competitions Mixed Architecture, Architectural Designs") &
                                (male_sports_df.Event != "Equestrianism Men's Jumping, Individual") &
                                (male_sports_df.Event != "Sailing Mixed Windsurfer") &
                                (male_sports_df.Event != "Snowboarding Men's Slopestyle") &
                                (male_sports_df.Event != "Athletics Men's 3,500 metres Walk") &
                                (male_sports_df.Event != "Athletics Men's 10 mile Walk") &
                                (male_sports_df.Event != "Cross Country Skiing Men's 18 kilometres") &
                                (male_sports_df.Event != "Equestrianism Men's Three-Day Event, Individual") &
                                (male_sports_df.Event != "Athletics Men's 2,500 metres Steeplechase") &
                                (male_sports_df.Event != "Athletics Men's Javelin Throw, Both Hands") &
                                (male_sports_df.Event != "Athletics Men's 3,200 metres Steeplechase") &
                                (male_sports_df.Event != "Wrestling Men's Unlimited Class, Greco-Roman") &
                                (male_sports_df.Event != "Gymnastics Men's Team All-Around, Swedish System") &
                                (male_sports_df.Event != "Athletics Men's Discus Throw, Both Hands") &
                                (male_sports_df.Event != "Athletics Men's 5 mile") &
                                (male_sports_df.Event != "Snowboarding Men's Parallel Slalom") &
                                (male_sports_df.Event != "Athletics Men's 2,590 metres Steeplechase") &
                                (male_sports_df.Event != "Athletics Men's Pentathlon (Ancient)") &
                                (male_sports_df.Event != "Snowboarding Men's Giant Slalom") &
                                (male_sports_df.Event != "Gymnastics Men's Parallel Bars, Teams") &
                                (male_sports_df.Event != "Gymnastics Men's Horizontal Bar, Teams") &
                                (male_sports_df.Event != "Swimming Men's One Mile Freestyle") &
                                (male_sports_df.Event != "Speed Skating Men's Allround") &
                                (male_sports_df.Event != "Canoeing Men's Canadian Doubles, 10,000 metres") &
                                (male_sports_df.Event != "Cross Country Skiing Men's 10 kilometres") &
                                (male_sports_df.Event != "Swimming Men's 50 yard Freestyle") &
                                (male_sports_df.Event != "Swimming Men's 100 yard Freestyle") &
                                (male_sports_df.Event != "Swimming Men's 4 x 250 metres Freestyle Relay") &
                                (male_sports_df.Event != "Freestyle Skiing Men's Halfpipe") &
                                (male_sports_df.Event != "Athletics Men's Shot Put, Both Hands") &
                                (male_sports_df.Event != "Athletics Men's 3 mile, Team") &
                                (male_sports_df.Event != "Cross Country Skiing Men's 10/10 kilometres Pursuit") &
                                (male_sports_df.Event != "Athletics Men's Standing Triple Jump") &
                                (male_sports_df.Event != "Art Competitions Mixed Literature") &
                                (male_sports_df.Event != "Athletics Men's All-Around Championship") &
                                (male_sports_df.Event != "Athletics Men's Discus Throw, Greek Style") &
                                (male_sports_df.Event != "Golf Men's Individual") &
                                (male_sports_df.Event != "Weightlifting Men's All-Around Dumbbell Contest") &
                                (male_sports_df.Event != "Nordic Combined Men's Normal Hill / 10 km, Individual") &
                                (male_sports_df.Event != "Weightlifting Men's Unlimited, One Hand") &
                                (male_sports_df.Event != "Equestrianism Men's Dressage, Team") &
                                (male_sports_df.Event != "Sailing Mixed 6 metres") &
                                (male_sports_df.Event != "Athletics Men's 200 metres Hurdles") &
                                (male_sports_df.Event != "Swimming Men's 1,000 metres Freestyle") &
                                (male_sports_df.Event != "Sailing Mixed 6 metres") &
                                (male_sports_df.Event != "Tennis Men's Singles, Covered Courts")
                                ]
# male_sports_df.head()

In [20]:

# Get unique name of event
event_list = male_sports_df.Event.unique()

# Create empty age, height, weight lists for storage
bronze_age_list = []
bronze_height_list = []
bronze_weight_list = []

for event_name in event_list:
    def event_function(event_name):
        
        # Filtering DataFrame for specific event name
        df = male_sports_df.loc[(male_sports_df['Event'] == event_name ),:]

        # Creating the Boxplot
        age_plot = df.loc[df['Event'] == event_name]['Age']
        height_plot = df.loc[df['Event'] == event_name]['Height']
        weight_plot = df.loc[df['Event'] == event_name]['Weight']

#         outlier_markers = dict(marker = 'o' , markerfacecolor='r', 
#                                markersize=5, markeredgecolor='r')
#         plt.boxplot([age_plot, height_plot, weight_plot], 
#                     labels=['Age', 'Height', 'Weight'], 
#                     flierprops=outlier_markers)
#         plt.ylabel('Bronze Medals')
#         plt.title(f'Male-{event_name}')

#         #plt.savefig(f'Male-Sport-Events/Plots/male-{event_name}.png')
#         plt.show()

        # Calculate the quartiles
        age_quartiles = age_plot.quantile([.25,.5,.75])
        height_quartiles = height_plot.quantile([.25,.5,.75])
        weight_quartiles = weight_plot.quantile([.25,.5,.75])
        
        # Creating age list
        age = round(age_quartiles[.5])
        bronze_age_list.append(age)
        
        # Creating height list - converting Metric System to Imperial system
        height = (height_quartiles[.5])/30.48
        bronze_height_list.append("%.2f"%height)
        
        # Creating weight list - converting Metric System to Imperial system
        weight = (weight_quartiles[.5])*2.205
        bronze_weight_list.append("%.2f"%weight)
        
    event_function(event_name)
# print(f'Bronze Age List: {bronze_age_list}')
# print(f'Bronze Height List: {bronze_height_list}')
# print(f'Bronze Weight List: {bronze_weight_list}')

In [21]:
# Finding out length of list 
print(len(bronze_age_list))
print(len(bronze_height_list))
print(len(bronze_weight_list))
print(len(event_list))

289
289
289
289

In [22]:
# Storing values from list to make a DataFrame
bronze_dictionary = {"Event":event_list,"Age":bronze_age_list, "Height": bronze_height_list, 
                    "Weight":bronze_weight_list, "Sex": "Male" }

bronze_bodycomp_age_df = pd.DataFrame(bronze_dictionary)
bronze_bodycomp_age_df

                                           Event   Age Height  Weight   Sex
0                    Ice Hockey Men's Ice Hockey  26.0   5.97  185.22  Male
1         Gymnastics Men's Individual All-Around  24.0   5.48  141.12  Male
2               Gymnastics Men's Team All-Around  24.0   5.48  136.71  Male
3               Alpine Skiing Men's Giant Slalom  25.0   5.91  176.40  Male
4                    Alpine Skiing Men's Super G  26.0   5.87  194.04  Male
..                                           ...   ...    ...     ...   ...
284  Canoeing Men's Canadian Singles, 200 metres  24.0   5.82  188.53  Male
285    Athletics Men's 1,600 metres Medley Relay  18.0   5.97  160.97  Male
286           Athletics Men's Standing High Jump  22.0   6.10  164.27  Male
287                        Luge Mixed Team Relay  30.0   5.91  198.45  Male
288            Equestrianism Men's Jumping, Team  30.0   5.74  143.33  Male

[289 rows x 5 columns]

In [23]:
# Saving Dataframe into a csv file
bronze_bodycomp_age_df.to_csv('Male-Events/male_bronze_bodycomp_age.csv', index=False)

In [24]:
# Saving Dataframe into a JSON file
bronze_bodycomp_age_df.to_json('Male-Events/male_bronze_bodycomp_age.json')